name: integration tests passage-swift
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  PASSAGE_AUTH_TOKEN: ${{ secrets.PASSAGE_AUTH_TOKEN }}
  MAILOSAUR_API_KEY: ${{ secrets.MAILOSAUR_API_KEY }}

jobs:
  integration-test-iOS-18:
    name: Build and Integration Tests iOS
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Xcode 16
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.0'

      - name: List Schemes
        run: xcodebuild -list

      - name: Test iOS
        run: xcodebuild clean build-for-testing test -scheme Passage -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 15,OS=17.5" PASSAGE_AUTH_TOKEN="${{ env.PASSAGE_AUTH_TOKEN }}" MAILOSAUR_API_KEY="${{ secrets.MAILOSAUR_API_KEY }}" SWIFT_PACKAGE=YES -parallel-testing-enabled NO
