name: SwiftLint Check

on:
  pull_request:
    branches:
      - main

jobs:
  swiftlint:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install SwiftLint
      run: |
        brew install swiftlint

    - name: Run SwiftLint
      run: |
        swiftlint
